# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.12.15" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.12.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.12.15.tgz";
        sha512 = "AQBOU2Z9kWwSZMd6lNjCX0GUgFonL1wAM1db8L8PMk9UDaGsRCArBkU4Sc+UCM3AE4hjbXx+h58Lb3QT4oRmrA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "catharsis-0.8.11" = {
      name = "catharsis";
      packageName = "catharsis";
      version = "0.8.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/catharsis/-/catharsis-0.8.11.tgz";
        sha512 = "a+xUyMV7hD1BrDQA/3iPV7oc+6W26BgVJO05PGEoatMyIuPScQKsde6i3YorWX1qs+AZjnJ18NqdKoCtKiNh1g==";
      };
    };
    "entities-2.0.3" = {
      name = "entities";
      packageName = "entities";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.0.3.tgz";
        sha512 = "MyoZ0jgnLvB2X3Lg5HqpFmn1kybDiIfEQmKzTb5apr51Rb+T3KdmMiqa70T+bhGnyv7bQ6WMj2QMHpGMmlrUYQ==";
      };
    };
    "escape-string-regexp-2.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
        sha512 = "UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
      };
    };
    "graceful-fs-4.2.5" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.5.tgz";
        sha512 = "kBBSQbz2K0Nyn+31j/w36fUfxkBW9/gfwRWdUY1ULReH3iokVJgddZAFcD1D0xlgTmFxJCbUkUclAlc6/IDJkw==";
      };
    };
    "js2xmlparser-4.0.1" = {
      name = "js2xmlparser";
      packageName = "js2xmlparser";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-4.0.1.tgz";
        sha512 = "KrPTolcw6RocpYjdC7pL7v62e55q7qOMHvLX1UCLc5AAS8qeJ6nukarEJAF2KL2PZxlbGueEbINqZR2bDe/gUw==";
      };
    };
    "klaw-3.0.0" = {
      name = "klaw";
      packageName = "klaw";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/klaw/-/klaw-3.0.0.tgz";
        sha512 = "0Fo5oir+O9jnXu5EefYbVK+mHMBeEVEy2cmctR1O1NECcCkPRreJKrS6Qt/j3KC2C148Dfo9i3pCmCMsdqGr0g==";
      };
    };
    "linkify-it-2.2.0" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-2.2.0.tgz";
        sha512 = "GnAl/knGn+i1U/wjBz3akz2stz+HrHLsxMwHQGofCDfPvlf+gDKN58UtfmUquTY4/MXeE2x7k19KQmeoZi94Iw==";
      };
    };
    "lodash-4.17.20" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.20.tgz";
        sha512 = "PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA==";
      };
    };
    "markdown-it-10.0.0" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-10.0.0.tgz";
        sha512 = "YWOP1j7UbDNz+TumYP1kpwnP0aEa711cJjrAQrzd0UXlbJfc5aAq0F/PZHjiioqDC1NKgvIMX+o+9Bk7yuM2dg==";
      };
    };
    "markdown-it-anchor-5.3.0" = {
      name = "markdown-it-anchor";
      packageName = "markdown-it-anchor";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it-anchor/-/markdown-it-anchor-5.3.0.tgz";
        sha512 = "/V1MnLL/rgJ3jkMWo84UR+K+jF1cxNG1a+KwqeXqTIJ+jtA8aWSHuigx8lTzauiIjBDbwF3NcWQMotd0Dm39jA==";
      };
    };
    "marked-0.8.2" = {
      name = "marked";
      packageName = "marked";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.8.2.tgz";
        sha512 = "EGwzEeCcLniFX51DhTpmTom+dSA/MG/OBUDjnWtHbEnjAH180VzUeAw+oE4+Zv+CoYBWyRlYOTR0N8SO9R1PVw==";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "requizzle-0.2.3" = {
      name = "requizzle";
      packageName = "requizzle";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/requizzle/-/requizzle-0.2.3.tgz";
        sha512 = "YanoyJjykPxGHii0fZP0uUPEXpvqfBDxWV7s6GKAiiOsiqhX6vHNyW3Qzdmqp/iq/ExbhaGbVrjB4ruEVSM4GQ==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "taffydb-2.6.2" = {
      name = "taffydb";
      packageName = "taffydb";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/taffydb/-/taffydb-2.6.2.tgz";
        sha1 = "7cbcb64b5a141b6a2efc2c5d2c67b4e150b2a268";
      };
    };
    "uc.micro-1.0.6" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.6.tgz";
        sha512 = "8Y75pvTYkLJW2hWQHXxoqRgV7qb9B+9vFEtidML+7koHUFapnVJAZ6cKs+Qjz5Aw3aZWHMC6u0wJE3At+nSGwA==";
      };
    };
    "underscore-1.10.2" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.10.2.tgz";
        sha512 = "N4P+Q/BuyuEKFJ43B9gYuOj4TQUHXX+j2FqguVOpjkssLUUrnJofCcBccJSCoeturDoZU6GorDTHSvUDlSQbTg==";
      };
    };
    "xmlcreate-2.0.3" = {
      name = "xmlcreate";
      packageName = "xmlcreate";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlcreate/-/xmlcreate-2.0.3.tgz";
        sha512 = "HgS+X6zAztGa9zIK3Y3LXuJes33Lz9x+YyTxgrkIdabu2vqcGOWwdfCpf1hWLRrd553wd4QCDf6BBO6FfdsRiQ==";
      };
    };
  };
in
{
  jsdoc = nodeEnv.buildNodePackage {
    name = "jsdoc";
    packageName = "jsdoc";
    version = "3.6.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/jsdoc/-/jsdoc-3.6.6.tgz";
      sha512 = "znR99e1BHeyEkSvgDDpX0sTiTu+8aQyDl9DawrkOGZTTW8hv0deIFXx87114zJ7gRaDZKVQD/4tr1ifmJp9xhQ==";
    };
    dependencies = [
      sources."@babel/parser-7.12.15"
      sources."argparse-1.0.10"
      sources."bluebird-3.7.2"
      sources."catharsis-0.8.11"
      sources."entities-2.0.3"
      sources."escape-string-regexp-2.0.0"
      sources."graceful-fs-4.2.5"
      sources."js2xmlparser-4.0.1"
      sources."klaw-3.0.0"
      sources."linkify-it-2.2.0"
      sources."lodash-4.17.20"
      sources."markdown-it-10.0.0"
      sources."markdown-it-anchor-5.3.0"
      sources."marked-0.8.2"
      sources."mdurl-1.0.1"
      sources."mkdirp-1.0.4"
      sources."requizzle-0.2.3"
      sources."sprintf-js-1.0.3"
      sources."strip-json-comments-3.1.1"
      sources."taffydb-2.6.2"
      sources."uc.micro-1.0.6"
      sources."underscore-1.10.2"
      sources."xmlcreate-2.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An API documentation generator for JavaScript.";
      homepage = "https://github.com/jsdoc/jsdoc#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
